---
title: "homework2"
author: "Vivian"
date: "2021/10/23"
output: html_document
---
# Practice2

## Create the table

this table should be combined with the subject name and their weight before and after the experiment

```{get the table}
subiect<-c("sub1","sub2","sub3","sub4","sub5")
before_diet<-c(104,95,87,77,112)
after_diet<-c(96,91,81,75,118)
BUdiet<-data.frame(subiect,before_diet,after_diet)
```
BUdiet
  subiect before_diet after_diet
1    sub1         104         96
2    sub2          95         91
3    sub3          87         81
4    sub4          77         75
5    sub5         112        118


## Reformat the data

obtain the weight as a double numeric into one column and the time of measurement as factor with two levels 

```{reformat}
library(tidyr)
BUdiet_re<- BUdiet %>%  pivot_longer(cols=-subiect,names_to = c("time"),values_to = "weight")

```
BUdiet_re
A tibble: 10 x 3
   subiect time        weight
   <chr>   <chr>        <dbl>
 1 sub1    before_diet    104
 2 sub1    after_diet      96
 3 sub2    before_diet     95
 4 sub2    after_diet      91
 5 sub3    before_diet     87
 6 sub3    after_diet      81
 7 sub4    before_diet     77
 8 sub4    after_diet      75
 9 sub5    before_diet    112
10 sub5    after_diet     118


## Make other elements
 
There are 3 elements in the WEIGHT_LOSS list
1.subject name (already done)
2.the weight loss percent of each subject
3.a table combine with 1 &2

Let's do it!

```{elements}
percent<-(after_diet-before_diet)/before_diet*100
MIX<-data.frame(subiect,percent)
WEIGHT_LOSS<-list(subiect,percent_d,MIX)
```
percent
[1] -7.692308 -4.210526 -6.896552 -2.597403  5.357143
MIX
  subiect percent_d
1    sub1 -7.692308
2    sub2 -4.210526
3    sub3 -6.896552
4    sub4 -2.597403
5    sub5  5.357143
WEIGHT_LOSS
[[1]]
[1] "sub1" "sub2" "sub3" "sub4" "sub5"

[[2]]
[1] -7.692308 -4.210526 -6.896552 -2.597403  5.357143

[[3]]
  subiect percent_d
1    sub1 -7.692308
2    sub2 -4.210526
3    sub3 -6.896552
4    sub4 -2.597403
5    sub5  5.357143


## Combine all in one list

```{fin}
BUBBLE_DIET<-list(BUdiet_re,WEIGHT_LOSS)

```
 BUBBLE_DIET
[[1]]
 A tibble: 10 x 3
   subiect time        weight
   <chr>   <chr>        <dbl>
 1 sub1    before_diet    104
 2 sub1    after_diet      96
 3 sub2    before_diet     95
 4 sub2    after_diet      91
 5 sub3    before_diet     87
 6 sub3    after_diet      81
 7 sub4    before_diet     77
 8 sub4    after_diet      75
 9 sub5    before_diet    112
10 sub5    after_diet     118

[[2]]
[[2]][[1]]
[1] "sub1" "sub2" "sub3" "sub4" "sub5"

[[2]][[2]]
[1] -7.692308 -4.210526 -6.896552 -2.597403  5.357143

[[2]][[3]]
  subiect percent_d
1    sub1 -7.692308
2    sub2 -4.210526
3    sub3 -6.896552
4    sub4 -2.597403
5    sub5  5.357143
